/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicRouteRouteImport } from './routes/_public/route';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up';
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRouteRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof PublicRouteRouteWithChildren;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/sign-in': typeof PublicSignInRoute;
  '/sign-up': typeof PublicSignUpRoute;
}
export interface FileRoutesByTo {
  '/': typeof PublicRouteRouteWithChildren;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/sign-in': typeof PublicSignInRoute;
  '/sign-up': typeof PublicSignUpRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren;
  '/_public': typeof PublicRouteRouteWithChildren;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/_public/sign-in': typeof PublicSignInRoute;
  '/_public/sign-up': typeof PublicSignUpRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/dashboard' | '/sign-in' | '/sign-up';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/dashboard' | '/sign-in' | '/sign-up';
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/sign-in'
    | '/_public/sign-up';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  PublicRouteRoute: typeof PublicRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/sign-up': {
      id: '/_public/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof PublicSignUpRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_public/sign-in': {
      id: '/_public/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof PublicSignInRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

interface PublicRouteRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute;
  PublicSignUpRoute: typeof PublicSignUpRoute;
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
};

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
