/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './features/__root';
import { Route as PublicRouteRouteImport } from './features/_public/route';
import { Route as PublicAuthRouteRouteImport } from './features/_public/_auth/route';
import { Route as PublicAuthSignUpRouteRouteImport } from './features/_public/_auth/sign-up/route';
import { Route as PublicAuthSignInRouteRouteImport } from './features/_public/_auth/sign-in/route';

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicAuthSignUpRouteRoute = PublicAuthSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicAuthRouteRoute,
} as any);
const PublicAuthSignInRouteRoute = PublicAuthSignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicAuthRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof PublicAuthRouteRouteWithChildren;
  '/sign-in': typeof PublicAuthSignInRouteRoute;
  '/sign-up': typeof PublicAuthSignUpRouteRoute;
}
export interface FileRoutesByTo {
  '/': typeof PublicAuthRouteRouteWithChildren;
  '/sign-in': typeof PublicAuthSignInRouteRoute;
  '/sign-up': typeof PublicAuthSignUpRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_public': typeof PublicRouteRouteWithChildren;
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren;
  '/_public/_auth/sign-in': typeof PublicAuthSignInRouteRoute;
  '/_public/_auth/sign-up': typeof PublicAuthSignUpRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/sign-in' | '/sign-up';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/sign-in' | '/sign-up';
  id:
    | '__root__'
    | '/_public'
    | '/_public/_auth'
    | '/_public/_auth/sign-in'
    | '/_public/_auth/sign-up';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/_auth': {
      id: '/_public/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicAuthRouteRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_public/_auth/sign-up': {
      id: '/_public/_auth/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof PublicAuthSignUpRouteRouteImport;
      parentRoute: typeof PublicAuthRouteRoute;
    };
    '/_public/_auth/sign-in': {
      id: '/_public/_auth/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof PublicAuthSignInRouteRouteImport;
      parentRoute: typeof PublicAuthRouteRoute;
    };
  }
}

interface PublicAuthRouteRouteChildren {
  PublicAuthSignInRouteRoute: typeof PublicAuthSignInRouteRoute;
  PublicAuthSignUpRouteRoute: typeof PublicAuthSignUpRouteRoute;
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthSignInRouteRoute: PublicAuthSignInRouteRoute,
  PublicAuthSignUpRouteRoute: PublicAuthSignUpRouteRoute,
};

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
);

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren;
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
};

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
